name: PR Checks
on: pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Go 1.19.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-
      - name: Run linter and tests
        run: make check
